import "server-only";
import type { PersonaKey } from "@/config/personas";
import type { Role } from "@/domain/roles";
import type { BidStatus, HoldingStatus, InvestorType, ListingStatus } from "@/domain/types";
export const organizationSpecs = [
  ["buyer_a", "investor", "Palmgate Family Office"],
  ["buyer_b", "investor", "Investor B-117"],
  ["buyer_c", "investor", "Saffron Secondaries Fund I"],
  ["buyer_d", "investor", "Harbour Row Capital"],
  ["buyer_e", "investor", "Sidra Angels"],
  ["falaj", "company", "Falaj Robotics"],
  ["qamra", "company", "Qamra Health"],
  ["wadi", "company", "Wadi Ledger"],
  ["atlas", "operator", "Atlas"],
  ["dune", "investor", "Dune Logistics Ventures"],
] as const;
export const userSpecs: readonly {
  key: string;
  role: Role;
  handle: string;
  name: string;
  org: string | null;
  investorType: InvestorType | null;
  persona: PersonaKey | null;
}[] = [
  {
    key: "buyer_a",
    role: "buyer",
    handle: "Investor #B-081",
    name: "Palmgate Family Office",
    org: "buyer_a",
    investorType: "family_office",
    persona: "buyer_a",
  },
  {
    key: "buyer_b",
    role: "buyer",
    handle: "Investor #B-117",
    name: "Omar Qasim",
    org: "buyer_b",
    investorType: "hnwi",
    persona: "buyer_b",
  },
  {
    key: "buyer_c",
    role: "buyer",
    handle: "Investor #B-204",
    name: "Saffron Secondaries Fund I",
    org: "buyer_c",
    investorType: "fund",
    persona: null,
  },
  {
    key: "buyer_d",
    role: "buyer",
    handle: "Investor #B-352",
    name: "Harbour Row Capital",
    org: "buyer_d",
    investorType: "fund",
    persona: null,
  },
  {
    key: "buyer_e",
    role: "buyer",
    handle: "Investor #B-409",
    name: "Sidra Angels",
    org: "buyer_e",
    investorType: "angel_syndicate",
    persona: null,
  },
  {
    key: "seller",
    role: "seller",
    handle: "Holder #S-214",
    name: "Layla Haddad",
    org: null,
    investorType: null,
    persona: "seller",
  },
  {
    key: "seller_2",
    role: "seller",
    handle: "Holder #S-198",
    name: "Karim Nasser",
    org: null,
    investorType: null,
    persona: null,
  },
  {
    key: "seller_3",
    role: "seller",
    handle: "Holder #S-102",
    name: "Mira Rahman",
    org: null,
    investorType: null,
    persona: null,
  },
  {
    key: "company_admin",
    role: "company_admin",
    handle: "Falaj Robotics · CFO",
    name: "Hana Saleh",
    org: "falaj",
    investorType: null,
    persona: "company_admin",
  },
  {
    key: "qamra_admin",
    role: "company_admin",
    handle: "Qamra Health · Legal",
    name: "Yousef Darwish",
    org: "qamra",
    investorType: null,
    persona: null,
  },
  {
    key: "wadi_admin",
    role: "company_admin",
    handle: "Wadi Ledger · CFO",
    name: "Rania Aziz",
    org: "wadi",
    investorType: null,
    persona: null,
  },
  {
    key: "operator",
    role: "operator",
    handle: "Atlas compliance",
    name: "Noor Khalil",
    org: "atlas",
    investorType: null,
    persona: "operator",
  },
  {
    key: "operator_second",
    role: "operator",
    handle: "Atlas compliance · second approver",
    name: "Tariq Mansour",
    org: "atlas",
    investorType: null,
    persona: null,
  },
];
export const companySpecs = [
  {
    key: "falaj",
    slug: "falaj-robotics",
    name: "Falaj Robotics",
    sector: "Warehouse automation",
    stage: "Series B",
    incorporation: "ADGM",
    currency: "AED",
    description: "Robotic picking systems for warehouses in the Gulf.",
    round: "Series B",
    roundDays: 190,
    price: 4200n,
    postMoney: 46_200_000_000n,
    classes: [
      ["Series B preferred", 2_000_000n, 4200n],
      ["Series A preferred", 3_000_000n, 1200n],
      ["Ordinary", 6_000_000n, 0n],
    ],
    rofrDays: 30,
    minLot: 1000n,
    lockupMonths: 12,
    visibility: "participants",
    cap: 5000,
  },
  {
    key: "qamra",
    slug: "qamra-health",
    name: "Qamra Health",
    sector: "Health records software",
    stage: "Series A",
    incorporation: "DIFC",
    currency: "AED",
    description: "Patient records and billing software for private clinics.",
    round: "Series A",
    roundDays: 300,
    price: 1850n,
    postMoney: 16_650_000_000n,
    classes: [
      ["Series A preferred", 2_500_000n, 1850n],
      ["Seed preferred", 1_500_000n, 600n],
      ["Ordinary", 5_000_000n, 0n],
    ],
    rofrDays: 21,
    minLot: 500n,
    lockupMonths: 6,
    visibility: "operator",
    cap: 10000,
  },
  {
    key: "wadi",
    slug: "wadi-ledger",
    name: "Wadi Ledger",
    sector: "Payments infrastructure",
    stage: "Seed",
    incorporation: "DIFC",
    currency: "USD",
    description: "Payment rails and reconciliation for regional marketplaces.",
    round: "Seed",
    roundDays: 450,
    price: 320n,
    postMoney: 3_200_000_000n,
    classes: [
      ["Seed preferred", 3_000_000n, 320n],
      ["Ordinary", 7_000_000n, 0n],
    ],
    rofrDays: 30,
    minLot: 2000n,
    lockupMonths: 12,
    visibility: "members",
    cap: 10000,
  },
] as const;
export const holdingSpecs: readonly [
  string,
  string,
  string,
  bigint,
  bigint,
  bigint,
  number,
  HoldingStatus,
][] = [
  ["h_seller_falaj", "seller", "falaj", 30000n, 12000n, 0n, 1280, "Verified"],
  ["h_seller_wadi", "seller", "wadi", 10000n, 0n, 0n, 600, "Verified"],
  ["h_seller_qamra", "seller", "qamra", 4000n, 0n, 0n, 90, "Verified"],
  ["h_s198_falaj", "seller_2", "falaj", 12000n, 8000n, 4000n, 900, "Verified"],
  ["h_s102_falaj", "seller_3", "falaj", 3000n, 3000n, 0n, 1000, "Verified"],
  ["h_buyera_falaj", "buyer_a", "falaj", 4000n, 0n, 0n, 13, "Verified"],
];
export const listingSpecs: readonly [
  string,
  string,
  string,
  bigint,
  bigint,
  bigint,
  3 | 5 | 7,
  number,
  number,
  ListingStatus,
  number,
][] = [
  ["L-2031", "seller", "h_seller_falaj", 12000n, 2000n, 3400n, 7, -48, 120, "Live", 0],
  ["L-2027", "seller_2", "h_s198_falaj", 5500n, 5500n, 3450n, 7, -148, 20, "Live", 0],
  ["L-2019", "seller_3", "h_s102_falaj", 3000n, 1000n, 3500n, 5, -168, -48, "Negotiating", 1],
  ["L-2008", "seller_2", "h_s198_falaj", 6500n, 1000n, 3500n, 5, -600, -480, "Allocated", 0],
];
export const bidSpecs: readonly [string, string, bigint, bigint, bigint, number, BidStatus][] = [
  ["L-2031", "buyer_c", 3520n, 6000n, 2000n, -24, "Submitted"],
  ["L-2031", "buyer_d", 3480n, 12000n, 6000n, -20, "Submitted"],
  ["L-2027", "buyer_e", 3460n, 5500n, 5500n, -48, "Submitted"],
  ["L-2019", "buyer_a", 3400n, 3000n, 1000n, -96, "Countered"],
  ["L-2008", "buyer_a", 3580n, 4000n, 1000n, -552, "Accepted"],
  ["L-2008", "buyer_b", 3600n, 2500n, 1000n, -528, "Accepted"],
  ["L-2008", "buyer_c", 3450n, 3000n, 1000n, -528, "Rejected"],
];
export const printSpecs: readonly [string, bigint, bigint, number, boolean][] = [
  ["falaj", 3420n, 3000n, 160, false],
  ["falaj", 3500n, 2500n, 130, false],
  ["falaj", 3260n, 1500n, 100, false],
  ["falaj", 3610n, 3000n, 70, false],
  ["falaj", 3810n, 1000n, 40, false],
  ["falaj", 3580n, 4000n, 13, false],
  ["falaj", 2900n, 5000n, 60, true],
  ["wadi", 310n, 2000n, 150, false],
  ["wadi", 295n, 3000n, 90, false],
  ["wadi", 330n, 2500n, 30, false],
];
export const mandateSpecs: readonly [string, string, string[], string[]][] = [
  [
    "buyer_a",
    "Late-stage UAE tech",
    ["Warehouse automation", "Health records software"],
    ["Series B", "Series C"],
  ],
  ["buyer_b", "Early fintech", ["Payments infrastructure"], ["Seed", "Series A"]],
  [
    "buyer_c",
    "Secondaries — Gulf tech",
    ["Warehouse automation", "Payments infrastructure"],
    ["Seed", "Series B"],
  ],
  ["buyer_d", "Logistics", ["Warehouse automation"], ["Series B"]],
  [
    "buyer_e",
    "Angel follow-ons",
    ["Warehouse automation", "Health records software"],
    ["Series A", "Series B"],
  ],
];
export const qaSpecs = [
  {
    question: "Is there a liquidation preference ahead of ordinary shares?",
    answer:
      "Yes. Series A and Series B each hold a 1x non-participating preference; Series B ranks first.",
    askedDays: 5,
    answeredDays: 4,
  },
  {
    question: "Are you planning a new funding round in the next 12 months?",
    answer:
      "We don't comment on future rounds. The latest audited financials are in the info pack.",
    askedDays: 8,
    answeredDays: 7,
  },
  {
    question: "When will the FY2026 audited accounts be available?",
    answer: null,
    askedDays: 1,
    answeredDays: null,
  },
] as const;
