import { z } from "zod";

const name = z.string().regex(/^[a-z0-9][a-z0-9-]*$/);
const valueToken = z.object({ name, value: z.string(), usage: z.string().optional() });
const themedValue = z.object({ light: z.string(), dark: z.string() });
const schema = z.object({
  color: z.object({
    tokens: z.array(
      z.object({ name, value: z.union([z.string(), themedValue]), usage: z.string().optional() }),
    ),
  }),
  type: z.object({
    groups: z.array(
      z.object({
        name: z.string(),
        family: z.enum(["serif", "sans", "mono"]),
        styles: z.array(
          z.object({
            name,
            fontSize: z.string(),
            lineHeight: z.string(),
            fontWeight: z.number(),
            letterSpacing: z.string().optional(),
            sample: z.string(),
            usage: z.string().optional(),
          }),
        ),
      }),
    ),
  }),
  spacing: z.object({ tokens: z.array(valueToken) }),
  radius: z.object({ tokens: z.array(valueToken) }),
  shadow: z.object({ tokens: z.array(z.object({ name, value: themedValue })) }),
});

export type AtlasTokens = z.infer<typeof schema>;
type Theme = "light" | "dark";
const alias = /^\{([a-z0-9][a-z0-9-]*)\}$/;
const hex = /^#[0-9a-fA-F]{6}$/;

export function resolveColor(tokens: AtlasTokens, name: string, theme: Theme): string {
  const seen = new Set<string>();
  function resolve(current: string): string {
    if (seen.has(current)) throw new Error(`Invalid token ${name}: circular alias at ${current}`);
    seen.add(current);
    const token = tokens.color.tokens.find((item) => item.name === current);
    if (!token) throw new Error(`Invalid token ${name}: unknown alias ${current}`);
    const value = typeof token.value === "string" ? token.value : token.value[theme];
    const reference = alias.exec(value)?.[1];
    if (reference) return resolve(reference);
    if (!hex.test(value))
      throw new Error(`Invalid token ${current}: expected a six-digit hex for ${theme}`);
    return value;
  }
  return resolve(name);
}

export function parseTokens(json: unknown): AtlasTokens {
  const result = schema.safeParse(json);
  if (!result.success) {
    const messages = result.error.issues.map((issue) => {
      let source: unknown = json;
      let tokenName = "";
      for (const key of issue.path) {
        if (source && typeof source === "object") {
          if ("name" in source && typeof source.name === "string") tokenName = source.name;
          source = Reflect.get(source, key);
        }
      }
      return `${tokenName || issue.path.join(".")}: ${issue.message}`;
    });
    throw new Error(`Invalid tokens: ${messages.join("; ")}`);
  }
  const tokens = result.data;
  const names = new Set<string>();
  for (const token of [
    ...tokens.color.tokens,
    ...tokens.spacing.tokens,
    ...tokens.radius.tokens,
    ...tokens.shadow.tokens,
    ...tokens.type.groups.flatMap((group) => group.styles),
  ]) {
    if (names.has(token.name)) throw new Error(`Invalid token ${token.name}: duplicate name`);
    names.add(token.name);
  }
  for (const token of tokens.color.tokens) {
    resolveColor(tokens, token.name, "light");
    resolveColor(tokens, token.name, "dark");
  }
  if (!tokens.shadow.tokens.some((token) => token.name === "shadow-overlay")) {
    throw new Error("Invalid token shadow-overlay: missing shadow");
  }
  return tokens;
}

export function generateTokensCss(tokens: AtlasTokens): string {
  const blocks: string[] = [
    "/* GENERATED by scripts/build-tokens.ts from docs/design/tokens.json. Do not edit by hand. */",
  ];
  const block = (selector: string, lines: string[]) =>
    `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}`;
  for (const theme of ["light", "dark"] as const) {
    const lines = tokens.color.tokens.map((token) => {
      const raw = typeof token.value === "string" ? token.value : token.value[theme];
      const reference = alias.exec(raw)?.[1];
      return `--${token.name}: ${reference ? `var(--${reference})` : raw};`;
    });
    const shadow = tokens.shadow.tokens.find((token) => token.name === "shadow-overlay");
    if (!shadow) throw new Error("Missing shadow-overlay token");
    lines.push(`--elevation-overlay: ${shadow.value[theme]};`);
    blocks.push(
      block(theme === "light" ? ':root,\n[data-theme="light"]' : '[data-theme="dark"]', lines),
    );
  }
  blocks.push(
    block(
      ":root",
      tokens.spacing.tokens.map((token) => `--${token.name}: ${token.value};`),
    ),
  );
  blocks.push(
    block("@theme", [
      "--color-*: initial;",
      ...tokens.radius.tokens.map((token) => `--${token.name}: ${token.value};`),
    ]),
  );
  blocks.push(
    block("@theme inline", [
      ...tokens.color.tokens.map((token) => `--color-${token.name}: var(--${token.name});`),
      "--shadow-overlay: var(--elevation-overlay);",
    ]),
  );
  for (const group of tokens.type.groups) {
    for (const style of group.styles) {
      blocks.push(
        block(`@utility type-${style.name}`, [
          `font-family: var(--font-${group.family});`,
          `font-size: ${style.fontSize};`,
          `line-height: ${style.lineHeight};`,
          `font-weight: ${style.fontWeight};`,
          ...(style.letterSpacing ? [`letter-spacing: ${style.letterSpacing};`] : []),
          ...(group.name === "Figures" ? ["font-variant-numeric: tabular-nums;"] : []),
        ]),
      );
    }
  }
  return `${blocks.join("\n\n")}\n`;
}
